local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Giga Hub", "Midnight")
local Tab = Window:NewTab("LT2")
local Section = Tab:NewSection("Main")
Section:NewButton("Butter v2", "", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Butterisgood/Butter/main/lt2'))("")
end)
Section:NewButton("Dark X", "mod wood", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/darkxwin/darkxsourcethinkyoutousedarkx/main/darkx")()
end)
local Tab = Window:NewTab("PSX")
local Section = Tab:NewSection("Main")
Section:NewButton("Project WD", "", function()
    getgenv().boothsnipe = false
	loadstring(game:HttpGet("https://raw.githubusercontent.com/Muhammad6196/Project-WD/main/Mainstring.lua"))()
end)
Section:NewButton("Rafa Gui", " ...", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Rafacasari/roblox-scripts/main/psx.lua"))()
end)
local Tab = Window:NewTab("BloxFr")
local Section = Tab:NewSection("Main")
Section:NewButton("Auto Farm", "", function()
	_G.Key = "E3R-O399-NIL"
	loadstring(game:HttpGet(('https://raw.githubusercontent.com/BaconBABA/T-HUB/main/Main'),true))()
end)
Section:NewButton("Mukuru Hub", "", function()
	loadstring(game:HttpGet"https://raw.githubusercontent.com/xQuartyx/DonateMe/main/ScriptLoader")()
end)
local Tab = Window:NewTab("BSS")
local Section = Tab:NewSection("Main")
Section:NewButton("Family Club", "", function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/FamilyClub124/Loader/main/Family"))()
end)
Section:NewButton("Macro v2", "", function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/kyoichi35/Kyoichi-Hub/main/Kyoichi%20hub"))()
end)
local Tab = Window:NewTab("Pls Donate")
local Section = Tab:NewSection("Main")
Section:NewButton("Can Hub", "", function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/stuffman0001/CanHub/main/Code"))()
end)
Section:NewButton("Binary Hub", "", function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/BinaryHubOfficial/binaryhub/main/init.lua"))()
end)
local Tab = Window:NewTab("Arsenal")
local Section = Tab:NewSection("Main")
Section:NewButton("Thunder Client", "", function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/antipipka/roblox/main/Arsenal.lua"))()
end)
Section:NewButton("Osy Hub", "", function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/NullProtector/NullProtector.github.io/main/Osy%20%7BProtected%20By%20Moonsec%5D"))()
end)
local Tab = Window:NewTab("Da Hood")
local Section = Tab:NewSection("Main")
Section:NewButton("ScriptHubV2", "", function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/scripthubekitten/SCRIPTHUBV2/main/SCRIPTHUBV2", true))()
end)
Section:NewButton("Zinc Hub", "", function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/Zinzs/luascripting/main/canyoutellitsadahoodscriptornot.lua"))()
end)
local Tab = Window:NewTab("MM2")
local Section = Tab:NewSection("Main")
Section:NewButton("Kidachi", "", function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/KidichiHB/Kidachi/main/Scripts/MM2_V2"))()
end)
Section:NewButton("Admin Panel MM2", "", function()
	loadstring(game:HttpGet('https://raw.githubusercontent.com/woolips/tolis/main/77_7DBZZJU.lua'))()
end)
local Tab = Window:NewTab("TOH")
local Section = Tab:NewSection("Main")
Section:NewButton("Lightux", "", function()
	loadstring(game:HttpGet('https://raw.githubusercontent.com/woolips/tolis/main/77_7DBZZJU.lua'))()
end)
Section:NewButton("Weinz Hub", "", function()
	loadstring(game:HttpGet('https://raw.githubusercontent.com/weiny-ez/Weinz_Car-Dealership/main/weinz_cars.lua'))()
end)
local Tab = Window:NewTab("Other")
local Section = Tab:NewSection("Main")
Section:NewButton("Infinite yield", "", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source")()
end)
Section:NewButton("Dark Dex", "Studio", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Babyhamsta/RBLX_Scripts/main/Universal/BypassedDarkDexV3.lua", true))()
end)
Section:NewButton("Infinite yield", "", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source")()
end)
